# ---- Runtime image ----
FROM eclipse-temurin:17-jre

# Set working directory
WORKDIR /app

# Copy jar (generated by Maven)
COPY target/*.jar app.jar

# Expose application port (Spring Boot)
EXPOSE 8081

# JVM optimizations for containers
ENTRYPOINT ["java","-XX:+UseContainerSupport","-XX:MaxRAMPercentage=75.0","-jar","app.jar"]
